name: pipline_1

on:
    push:
        branches:
            - main

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: echo hello world
              run: echo "Hello, World!"
            
            - name: create folder
              run: mkdir session6

            - name: list folders
              run: ls -l
    
    job2: 
        runs-on: ubuntu-latest
        needs: [job-1, job-3]
        steps:
            - name: list folders
              run: ls -l

    job-3:
        runs-on: ubuntu-latest
        steps:
            - name: echo hello world again
              run: echo "Hello, World again!"